name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      statuses: write
      contents: write
      pages: write
  
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9.3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: julia --project=docs/ -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();'
  
      - name: Build and deploy
        run: julia --project=docs/ docs/make.jl

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
